export enum TransactionType {
  APPROVAL = 'APPROVAL',
  BUILD_OVL_POSITION = 'BUILD_OVL_POSITION',
  UNWIND_OVL_POSITION = 'UNWIND_OVL_POSITION',
  LIQUIDATE_OVL_POSITION = 'LIQUIDATE_OVL_POSITION',
  BRIDGE_OVL = 'BRIDGE_OVL',
  CLAIM_OVL = 'CLAIM_OVL',
  REFERRAL_CREATE_AFFILIATE = 'REFERRAL_CREATE_AFFILIATE',
  REFERRAL_CLAIM = 'REFERRAL_CLAIM',
}