export enum TransactionType {
  APPROVAL = 'APPROVAL',
  BUILD_OVL_POSITION = 'BUILD_OVL_POSITION',
  UNWIND_OVL_POSITION = 'UNWIND_OVL_POSITION',
  LIQUIDATE_OVL_POSITION = 'LIQUIDATE_OVL_POSITION',
  CLAIM_REWARDS = 'CLAIM_REWARDS',
  STAKE_OVL = 'STAKE_OVL',
  WITHDRAW_OVL = 'WITHDRAW_OVL',
}